# Generated by Django 4.1.4 on 2022-12-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snu_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
