# Generated by Django 4.1.4 on 2022-12-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snu_student', '0003_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
