# Generated by Django 4.1.4 on 2023-01-02 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snu_student', '0004_rename_username_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('curriculum', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('grade', models.IntegerField(blank=True, default=0)),
                ('number', models.CharField(max_length=100)),
                ('class_number', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='^[0-9]{3}$')])),
                ('maximum', models.IntegerField()),
                ('current', models.IntegerField(blank=True, default=0)),
                ('time', models.CharField(blank=True, default='', max_length=100)),
                ('credit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('lecture', models.IntegerField()),
                ('lab', models.IntegerField()),
                ('form', models.CharField(blank=True, default='', max_length=100)),
                ('classroom', models.CharField(blank=True, default='', max_length=100)),
                ('cart', models.IntegerField(blank=True, default=0)),
                ('rate', models.IntegerField(null=True)),
            ],
        ),
    ]
