# Generated by Django 4.1.4 on 2023-01-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snu_student', '0005_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
